### PR TITLE
Add discord webhook

### PR DESCRIPTION
**Pull request by nes0**
Hopefully this change replaces UserObserver Slack posts with a post to a Discord webhook URL which will be retrieved from the production environment. I don't know PHP or Laravel, so would really appreciate it if you would check this over for correctness. I've tried to keep it as simple as possible.

### CODE REVIEW

**Comment by ArthurGuy** [comment]
It's hard to tell without testing it but it should be ok, it can also be wrapped in an exception try/catch block in case there is an error.
Do you have the value for the environment variable  `DISCORD_WEBHOOK`?

**Comment by nes0** [comment]
Thanks Arthur. Yes I have a value for DISCORD_WEBHOOK. I don't have access to the production environment though. I'm hoping someone else can help with that. Shall I email it to you?

**Comment by nes0** [comment]
I've just added an exception handler which should log in the event of any obvious failure.

**Comment by paters936** [comment]
DMed you the hook

**Comment by ArthurGuy** [comment]
Hey guys, the key has been added to the environment file and should be good to go

**Comment by nes0** [comment]
Thanks Arthur. Shall we deploy this change and see if it works?

**Comment by paters936** [comment]
Looks good

**Pull request merged**
